version: '3'

services:
  postgresql_db:
    restart: always
    image: postgres
    ports:
      - '5433:5432'
    networks:
      - rest_api_university
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: api
    ports:
      - '5000:5000'
    depends_on:
      - postgresql_db
    networks:
      - rest_api_university

networks:
  rest_api_university:
    driver: bridge