swagger: '2.0'
info:
  title: 'University API'
  description: 'This is API for working with university data.'
  contact:
    email: shikhanovivan@gmail.com
    url: https://github.com/VanderSVan/Task_10_PSQL_Rest_API
  version: '1.0.0'
host: 127.0.0.1:5000
schemes: [http]

definitions:
  student:
    type: object
    properties:
      student_id:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      group_name:
        type: string
      course_names:
        type: string
  students:
    type: array
    items:
      properties:
        student_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        group_name:
          type: string
        course_names:
          type: string
  full_student:
    type: object
    properties:
      student_id:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
      group:
        type: object
        properties:
          groip_id:
            type: integer
          name:
            type: string
      courses:
        type: array
        items:
          properties:
            course_id:
              type: integer
            name:
              type: string
            description:
              type: string
  full_students:
    type: array
    items:
      properties:
        student_id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        group:
          type: object
          properties:
            groip_id:
              type: integer
            name:
              type: string
        courses:
          type: array
          items:
            properties:
              course_id:
                type: integer
              name:
                type: string
              description:
                type: string
  groups:
    type: object
    properties:
      group_id:
        type: string
      name:
        type: string
      students:
        type: array
        items:
          type: integer
  courses:
    type: object
    properties:
      course_id:
        type: string
      name:
        type: string
      description:
        type: string
      students:
        type: array
        items:
          type: integer